name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: RawZ06-Studio/.github/.github/workflows/node-ci-release.yml@main
    permissions:
      contents: write
    with:
      publishable: false       # application, pas de publish npm
    secrets: inherit

  docker:
    needs: release
    uses: RawZ06-Studio/.github/.github/workflows/docker-build-push.yml@main
    permissions:
      contents: write   # Nécessaire pour les tags/releases
      packages: write   # Nécessaire pour Docker/Maven/NPM
    with:
      image_name: geoguessr
      dokploy_app_id: iSkpHmNV4xSD726hQvQzS
    secrets: inherit
